### ISSUE TITLE
Can't access web application

### ISSUE THREAD

**Issue by cnmoro** [ironmussa/Bumblebee#102]
After running the application via docker, I get a prompt saying the Bumblebee process is running, and also the Jupyter Kernel, but I can't access it through the web browser. Am I missing something ?

`
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2][ERROR] Process or Namespace api not found
[PM2][ERROR] Process or Namespace web not found
[PM2][ERROR] Process or Namespace api not found
[PM2] Starting /usr/bin/bash in fork_mode (1 instance)
[PM2] Done.
┌─────┬────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name   │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ web    │ default     │ N/A     │ fork    │ 55       │ 0s     │ 0    │ online    │ 0%       │ 21.5mb   │ root     │ disabled │
└─────┴────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2] Starting /usr/bin/bash in fork_mode (1 instance)
[PM2] Done.
┌─────┬────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name   │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ api    │ default     │ N/A     │ fork    │ 84       │ 0s     │ 0    │ online    │ 0%       │ 3.5mb    │ root     │ disabled │
│ 0   │ web    │ default     │ N/A     │ fork    │ 77       │ 0s     │ 1    │ online    │ 0%       │ 28.8mb   │ root     │ disabled │
└─────┴────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[Bumblebee] Web process at: http://192.168.30.224:3000
[KernelGatewayApp] Jupyter Kernel Gateway at http://127.0.0.1:8888
`

**Comment by luis11011** [comment]
It takes some time before Bumblebee is available, try waiting a few minutes before trying to open the web app.

Otherwise, try entering your Docker container using `docker exec -it <CONTAINER NAME> bash` and run `pm2 log web` to see if there's some error.

**Comment by cnmoro** [comment]
> It takes some time before Bumblebee is available, try waiting a few minutes before trying to open the web app.
> 
> Otherwise, try entering your Docker container using `docker exec -it <CONTAINER NAME> bash` and run `pm2 log web` to see if there's an error.

If I use the following command to run it:
$ docker run --name bbee --network="host" -e ADDRESS=192.168.30.187 ironmussa/bumblebee:develop-3.0
Then
'pm2 log web' gives me the following error:
0|web      | error Couldn't find a package.json file in "/"

If I use this other command:
$ docker run --name bumblebee -P -e ADDRESS=localhost ironmussa/bumblebee:develop-3.0
Then
'pm2 log web' gives me this:
0|web  |  READY  Server listening on http://0.0.0.0:3000

But I still can't access it through the browser :(

**Comment by luis11011** [comment]
In which of the two commands you tried you are able to access to `localhost:4000` or `192.168.30.187:4000`? This is our slack channel in case you want to share your case through here https://hi-bumblebee.slack.com/archives/C014QGEFZ0W

**Comment by cnmoro** [comment]
I was able to access localhost:3000 by mapping the port from docker to the host, using -p 3000:3000
I am greeted by a login screen but cant create an account (error when filling form to sign up)
![image](https://user-images.githubusercontent.com/21183273/107104086-f97cec80-67fe-11eb-81e4-3d5a11e87086.png)

**Comment by luis11011** [comment]
Add `-p 4000:4000` too, that should do it

**Comment by cnmoro** [comment]
it worked, thanks !
