### ISSUE TITLE
Reportedly missing files.

### ISSUE THREAD

**Issue by GholG** [ironmussa/Bumblebee#105]
Hello,

I'm finding this a bit strange but it looks simple enough.

I'm following this article and setting up BubbleBee but at 

```
bash bbi.sh start environment
```
There are some errors about the files `start-bubblebee.sh` and `start-jupyter.sh` missing. The files are strangely present in the ../scripts directory. And the script happens to find two of the other source files.

Any ideas what exactly could be wrong here?

**Comment by luis11011** [comment]
What version of Ubuntu are you using? A few commits ago we implemented those scripts to use bash instead of sh, could you try again and confirm if it works for you?

**Comment by GholG** [comment]
```
(base) root@ubuntu-s-1vcpu-2gb-intel-nyc3-01:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
(base) root@ubuntu-s-1vcpu-2gb-intel-nyc3-01:~#
 ```
Bash

```
(base) root@ubuntu-s-1vcpu-2gb-intel-nyc3-01:~# echo $BASH_VERSION
5.0.17(1)-release
```

We had to make some changes ourselves. It seems like the script `bbi.sh` is supposed to run wholy in the ./scripts directory but `install_optimus.sh` moves it to a different directory and never places is back to ./scripts.
