### ISSUE TITLE
Bumblebee cannot load data

### ISSUE THREAD

**Issue by GholG** [ironmussa/Bumblebee#107]
Hello,

We are currently stuck with bumblebee not being able to load any data. 

The error points to some typescript kernel code but being new to bumblebee, it has not been possible for us to debug this any further.

This is the operation

![image](https://user-images.githubusercontent.com/51019843/111467051-0e6d6980-8735-11eb-85a8-69202a47cc4c.png)

This is what we get from the console

![image](https://user-images.githubusercontent.com/51019843/111467309-57252280-8735-11eb-95d3-b4a7e126a336.png)

Could someone happen to know what exactly is happening? 

Thanks in advance!

**Comment by luis11011** [comment]
Hi,

This error is now fixed, it was an error on Optimus.

You can now update bumblebee using `git pull` and the optimus library using pip or `bash bbi.sh update optimus`. Or in case you were using Docker, just pull the image again.

**Comment by argenisleon** [comment]
Thanks for the comment @GholG.
We are working to better handle the interaction between Optimus and Bumblebee.
You will see a lot of improvements in the next weeks.
