### ISSUE TITLE
Encountered Initialization error on setting up a workspace 

### ISSUE THREAD

**Issue by BirukAbreham** [ironmussa/Bumblebee#131]
Hello guys I am trying to set up a development environment for customizing this project on a virtual VM of Ubuntu 20.04.

- After creating a test workspace on the bumblebee, when I try to work on it I encountered this issue

![engine_setting_error](https://user-images.githubusercontent.com/24637978/124956524-bed2e680-e020-11eb-9707-3ccaf28e30d2.png)

- The node process for the front-end and the back-end are running on port 3000 and 4000 respectively
- The `jupyter_getway` is running on port 8888
- The VM environment is as follows
   - Ubuntu 20.04
   - MongoDB 4.4
   - conda 4.10.1 
    - Node.js v12.22.1
- Any help will be appreciated.

**Comment by luis11011** [comment]
Hi Biruk,

What's showing on the console?

We have been getting a similar error since we started stress testing the app, it seems that is due the capacity of the Jupyter Kernel Gateway and we're currently working on alternatives for that. Did you try again?

**Comment by BirukAbreham** [comment]
Hey,

Yes, I did try it several times. In the console, there is a `Timeout Error`

**Comment by luis11011** [comment]
It's possible that the jupyter kernelgateway process is running in the correct port but in a different address. If it's running in `0.0.0.0` you'll encounter problems accessing the gateway via the same machine. Make sure you have the address properly configured.

I'll recreate your environment and let you know if there's a quick fix.

**Comment by BirukAbreham** [comment]
Ok, I will try to change the IP and will post if I resolve the issue. Thank you for your quick response.

**Comment by luis11011** [comment]
I have tested this several times using a local installation and a Docker image, it seems okay so I'm closing this issue.
