### ISSUE TITLE
Explore how to improve the toolbar 

### ISSUE THREAD

**Issue by argenisleon** [ironmussa/Bumblebee#150]
It can be difficult for some users to navigate +100 functions. Adding descriptions could help. Here is an excel example.

![image](https://user-images.githubusercontent.com/37144/134516808-7b5b342a-8065-492e-a8a1-66cb121507cd.png)

**Comment by luis11011** [comment]
Labels were added but this may still require to label the sections.

![image](https://user-images.githubusercontent.com/53626283/135634754-0a7bf4bb-30d1-4cf7-a6fc-742f5590c9b5.png)
