### ISSUE TITLE
Unable to login in docker

### ISSUE THREAD

**Issue by ghost** [ironmussa/Bumblebee#164]
docker run --name mybee -p 3000:3000 -p 4000:4000 -e ADDRESS=192.168.1.3 hiprimus/bumblebee:latest
Login page is visible on chrome, however all attempts to create new login or clicking "sign in" button shows following error 
"SyntaxError: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL"
![image](https://user-images.githubusercontent.com/85286693/138635441-2127ef4d-20a5-4ada-81c3-b0fdc13fedb9.png)

**Comment by luis11011** [comment]
Hi ashitabhkumar,

Follow [this guide](https://medium.com/hi-bumblebee/how-to-run-bumblebee-in-a-docker-container-c9da047d1ff1) to use a Docker Container in a remote host.

**Comment by ghost** [comment]
Thanks Luis,
I was using Docker on windows 10 , which is not supported as per your documentation 
(https://github.com/hi-primus/bumblebee/blob/develop-21.9/docs/install-bumblebee/install-via-docker.md)
"Please have in mind the host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server. "
