### ISSUE TITLE
when trying to signup, getting error "User not found"

### ISSUE THREAD

**Issue by ramprasadsharma72** [ironmussa/Bumblebee#171]
**Describe the bug**
Try to sign up and you will get the error "User not found"

in the console, you will get the malformed URL..

and while checking the web-out.log, you will get connection refused..

**Comment by argenisleon** [comment]
@ramprasadsharma72 transferring this issue to the Bumblebee repo.
@luis11011 can you check this?

**Comment by luis11011** [comment]
@ramprasadsharma72 Could please let us know if you're using a Docker Container? Also it would be helpful if you could send to us the content of the browser console to check the errors you get.
