### ISSUE TITLE
Cannot access secondary GPU - error: [XORG] (EE) Problem parsing the config file

### ISSUE THREAD

**Issue by Preppyprep** [ironmussa/Bumblebee#174]
Hey. 
(Before we begin, please consider me a newbie.)

I am on my Endeavour OS migrating from Pop OS, and I have done every possible step in arch's bumblebee wiki to get it to run/fix (I have skipped some, such as displacing intel configuration file, because there is just no file).

I get the same error, here is it:
```
[16438.975272] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Problem parsing the config file

[16438.975302] [ERROR]Aborting because fallback start is disabled.
```
Here are my configurations: 
GPU: NVIDIA GeForce 930MX 
GPU: Intel Skylake GT2 [HD Graphics

**Comment by argenisleon** [comment]
Hi @YuvrajDadheech

Not sure if this is a CUDA driver problem or a Bumblebee/Optimus problem?

Can you show us the script you are running?

Ing. Argenis Leon, Dr.
CDMX, Mexico
Movil: 525541356726

Sent via Superhuman ( ***@***.*** )
