### ISSUE TITLE
Login issue with bumblebee

### ISSUE THREAD

**Issue by nagarajmmu** [ironmussa/Bumblebee#178]
Hi 

I have installed bumblebee for my project, everything works fine, till it load bumblebee login page.
When I try to register in bumblebee login page (installed bumblebee login HTTP://HOST_IP:3000/login), it was trying to hit HTTPS://HOST_IP:443/auth/signup , Says Network error. But when I have verified, nothing was running in 443 port.
I was running application in HTTP. it was trying to hit with HTTPS, also for auth URL it is using 443.

I have installed using docker image, using below command,
#_docker run --name bumblebee --network="host" -p 4000:4000 -e ADDRESS=HOST_IP hiprimus/bumblebee:develop_

How to resolve this issue.

**Comment by luis11011** [comment]
Hi,

You should expose the port you configured, in this case it seems it can be done by using `-p 443:443` and remember to configure the port of the backed using `-e BACK_PORT=443` so it will look something like:

`docker run --name bumblebee --network="host" -p 3000:3000 -p 443:443 -e ADDRESS=HOST_IP -e BACK_PORT=443 hiprimus/bumblebee:develop`

**Comment by argenisleon** [comment]
Hi @nagarajmmu,

Does this work for you?
