### ISSUE TITLE
Installation link isn't working

### ISSUE THREAD

**Issue by kaish114** [ironmussa/Bumblebee#21]
I tried opening the link [https://blog.hi-bumblebee.com/install-bumblebee/](https://blog.hi-bumblebee.com/install-bumblebee/) but it shows connection has timed out.
![image](https://user-images.githubusercontent.com/32337116/76557919-69d19f80-64c2-11ea-9ab8-49bec5a2c7e2.png)

**Comment by argenisleon** [comment]
Hi @kaish114 ,
You can get instructions for multiple installations here.
https://medium.com/hi-bumblebee

Where did get the link so I can fix it?!

**Comment by kaish114** [comment]
Thanks, @argenisleon for help.
I got the link from README.md

![image](https://user-images.githubusercontent.com/32337116/76564913-89bb9000-64cf-11ea-8902-5a404a886be6.png)

**Comment by argenisleon** [comment]
Fixed!

**Comment by kaish114** [comment]
Thank you @argenisleon
