### ISSUE TITLE
Getting some visual information in the Readme

### ISSUE THREAD

**Issue by FavioVazquez** [ironmussa/Bumblebee#7]
Hi I think we should be posting some visual information in the Readme so people have an idea of what it looks now, some screenshots or gifs would work.

Let me know your thoughts on this @argenisleon @JorgeParraAndrade

**Comment by argenisleon** [comment]
Yes,

We are working on some custom histogram that will be ready tomorrow and we will put it on the readme.

**Comment by FavioVazquez** [comment]
👍
