### ISSUE TITLE
docker install fail to load data

### ISSUE THREAD

**Issue by angelo337** [ironmussa/Bumblebee#70]
hi there
I am trying to work with the project, I manage to run it, using docker however when i try to load data from a web server in CSV format never load resources, and all time just continues saying something like this:

> [KernelGatewayApp] WARNING | No channel specified, assuming shell: {'header': {'msg_id': '37643663633266302d646235652d313165612d393966362d636639343837363530616230', 'session': '37643663633266302d646235652d313165612d393966362d636639343837363530616230', 'date': '2020-08-10T23:25:26.207Z', 'msg_type': 'execute_request'}, 'parent_header': {'msg_id': '37643663633266302d646235652d313165612d393966362d636639343837363530616230', 'session': '37643663633266302d646235652d313165612d393966362d636639343837363530616230', 'date': '2020-08-10T23:25:26.207Z', 'msg_type': 'execute_request'}, 'metadata': {}, 'content': {'code': '\n_status = \'kernel ok \'\n\ntry:\n\top\n\t_status += \'optimus ok \'+ op.__version__ + \' \'\n\ttry:\n\t\tdf\n\t\t_status += \'dataframe ok \'\n\texcept NameError:\n\t\t_status += \'\'\nexcept NameError:\n\tfrom optimus import Optimus\n\top = Optimus(master="local[*]", app_name="optimus", comm=True)\n\t_status = \'optimus init \' + op.__version__ + \' \'\n\n_status\n', 'silent': False}}
{ status: 'ok', content: '\'kernel ok optimus ok 2.2.29 \'' }
[KernelGatewayApp] Starting buffering for c1437d57-11f9-483e-b250-0c221b43c285:cc8e85a9-fdc5a0110784928e8da1566d

Could you please help me?
thanks a lot
angelo

**Comment by luis11011** [comment]
Hi Angelo, I can't identify your error, what's the unexpected behavior you are having?

Also, which branch did you clone?

**Comment by angelo337** [comment]
luis11011:
I just follow this guide:
[https://medium.com/hi-bumblebee/how-to-run-bumblebee-in-a-docker-container-c9da047d1ff1](url)

I am trying to test your tool with a docker container on my machine.

after finishing install i get the screen to upload data from a CSV file but i never get the data in there.

thanks for your answer
angelo

**Comment by argenisleon** [comment]
Hi @angelo33,

We are in the middle of a big refactoring that we expect to finish in a couple of days.
We will be reviewing your issue and let you know a fix.

Thanks

**Comment by angelo337** [comment]
Hi @argenisleon 
Do you have any news for this issue Please?,
as I follow your latest release but I am unable to install with this Guide either:
[https://medium.com/hi-bumblebee/install-bumblebee-from-scratch-on-google-cloud-platform-3c6dce13587b](https://medium.com/hi-bumblebee/install-bumblebee-from-scratch-on-google-cloud-platform-3c6dce13587b)

thanks a Lot
Angelo

**Comment by argenisleon** [comment]
Hi @angelo337,

Could you join the slack channel https://join.slack.com/t/hi-bumblebee/shared_invite/zt-evy3pz9h-gGjkD2Oy26PihxRD~Jg2fw?
I think we can give you better support from there.

**Comment by luis11011** [comment]
Installation guides where updated weeks ago

**Comment by angelo337** [comment]
hi there
I just re-install all docker container with this command:

docker pull ironmussa/bumblebee:develop-3.0

docker run --name bumble --network="host" -e ADDRESS=192.168.1.110 -e SPARK=true ironmussa/bumblebee:develop-3.0

Now i am able to run the container however when I get workspace page keep said:
Loading workspace

and I am stuck in there

thanks a lot

**Comment by luis11011** [comment]
Hi @angelo337,

Depending on your hardware the initialization of the kernel may take some extra time. Could you please turn on the verbose option on your browser console and let us know if there is an error? If not please try again.

Also you can enter to http://192.168.1.110/api/kernels to see if the kernel is being created for your session.

**Comment by angelo337** [comment]
URL: http://192.168.1.110:3000/api/kernels
output: Error { "statusCode": 404, "path": "/api/kernels", "message": "This page could not be found" }

**Comment by luis11011** [comment]
Sorry, I meant http://192.168.1.110:8888/api/kernels

**Comment by angelo337** [comment]
http://192.168.1.110:8888/api/kernels

Unable to connect   Firefox can’t establish a connection to the server at 192.168.1.110:8888.

**Comment by luis11011** [comment]
Just pushed a fix and I'm uploading a new image to Docker Hub, please try pulling again in a few minutes
